apiVersion: 3
dataDisplay:
  textFormats:
    layout-orig-full: 
      method: layout
  textFormat: layout-orig-full
  excludedFeatures: []
  noneValues:
  - none
  - unknown
  - null
  - NA
  sectionSep1: "@"
docs:
  docPage: about
  featureBase: '{docBase}/transcription.md'
  featurePage: transcription
interfaceDefaults: 
  fmt: layout-orig-full
provenanceSpec:
  corpus: '{org} - {repo}{relative}'
  doi: 10.5281/zenodo.notyet
  moduleSpecs: []
  version: «version»
  webBase: 'https://public.{org}.org/{repo}'
  webHint: Show this on the website
  webLang: en
  webUrl: '{webBase}/<1>/<2>/<3>&version={version}'
  webUrlLex: '{webBase}/word?version={version}&id=<lid>'
typeDisplay: {}
writing: ''
